New ingress controller configuration action required message
openshift/managed-notifications pull request #14
Opened 2021-04-08 21:18 UTC by robotmaxtron

2021-04-08 21:19 UTC, robotmaxtron commented
cc: @aweiteka

2021-04-09 13:29 UTC, aweiteka requested changes

2021-04-09 13:29 UTC, aweiteka commented on osd/Ingress-Controllers.json
> +    "summary": "Ingress controller blocked, action required",
Typical summary convention has been this pattern, "Action required: Update ingress controller configuration"

2021-04-09 13:29 UTC, aweiteka commented on osd/Ingress-Controllers.json
> +    "description": "Your cluster has a configuration problem with ingress-controllers. Ingress Operator configuration documentation can be found here - https://docs.openshift.com/container-platform/4
Let's call out the cause and action more explicitly.

"Your cluster has a misconfigured ingress-controller. Please delete the ingress controller and create a new one that does not conflict. See documentation documentation can be found here - https://docs.openshift.com/container-platform/4.7/networking/ingress-operator.html#configuring-ingress-controller",
 

 
Let's call out the cause and action more explicitly.

"Your cluster has a misconfigured ingress-controller. Please delete the ingress controller and create a new one that does not conflict. See ingress-controller documentation for details: https://docs.openshift.com/container-platform/4.7/networking/ingress-operator.html#configuring-ingress-controller"

I'm not clear on the conflict part (CIDR?). Let's make this work generally for all ingress-controller issues.

2021-04-29 14:36 UTC, robotmaxtron commented
Updated the wording as requested.

2021-04-29 14:41 UTC, cattias commented
/lgtm

2021-04-29 14:42 UTC, merged