add template for general logging issue for rosa clsuters
openshift/managed-notifications pull request #48
Opened 2021-05-28 05:53 UTC by bmeng

2021-06-01 12:55 UTC, aweiteka requested changes

2021-06-01 12:55 UTC, aweiteka commented on osd/rosa_clusterlogging_general.json
> + "description": "Your cluster requires you to take action. Your cluster has problems on the Cluster Logging service which includes but is not limited to cluster logging operator, fluentd. Please refe
As a customer I wouldn't have much confidence that I could find and resolve this issue. cluster-logging-operator, fluentd and possibly other components? I believe fluentd is part of cluster-logging-operator. Can we be more specific? Would going through the docs "Verification steps" be the best place to start?

2021-07-19 08:47 UTC, bmeng commented
@aweiteka  sorry for missing the comment here. Have update the message, please take a look again.

2021-08-19 07:38 UTC, cattias commented
/lgtm

2021-08-19 07:43 UTC, merged